### PR TITLE
docs: change to mkdocs and google style

### PR DESCRIPTION
**Pull request by hfudev**
also update docs

### CODE REVIEW

**Comment by igrr** [comment]
Perhaps now that we aren't using the Gitlab repo, we should also add an action to deploy the docs somewhere public? Like https://github.com/mhausenblas/mkdocs-deploy-gh-pages.

**Comment by hfudev** [comment]
@igrr since we're using https://docs.espressif.com/projects/pytest-embedded/en/latest/ to host it and `readthedocs` also supports `mkdocs`, should we try to deploy to the same place?

**Comment by igrr** [comment]
My bad, i forgot that we host this on RTD already!

RTD has "build type" as a global setting only, so I have switched it from Sphinx to mkdocs. This means that the docs on the master branch are likely broken now. The docs for this branch on RTD currently fails because of the missing `pytest-embedded` dependency. Once it is fixed, the docs will be available at https://readthedocs.com/projects/espressif-pytest-embedded/builds/695925/.

**Comment by hfudev** [comment]
@igrr here I'm using the `.readthedocs.yaml` for the build process and it's working. PTAL. https://docs.espressif.com/projects/pytest-embedded/en/docs-update_docs_and_examples/

**Pull request merged**
