### PR TITLE
fix cli option "--erase-flash" conflict with function `erase_flash()`

### PR DESCRIPTION
**Pull request by hfudev**
fix regression from https://github.com/espressif/pytest-embedded/pull/98

### CODE REVIEW

**Comment by hfudev** [comment]
@Ouss4 PTAL.

**Comment by hfudev** [comment]
yanked 0.7.4

**Review by Ouss4 — APPROVED** [review]
Ah so it ended up conflicting with the function... I did have concerns that this may happen.
Thanks for the fix @hfudev.

**Comment by hfudev** [comment]
added some tests

**Pull request merged**
